### ISSUE TITLE
Tamanho Aba descrição 

### ISSUE THREAD

**Issue by jasmimdsantos** [Terravisiongeo/tvgeo#20]
•	Na Aba “Criar Impacto” o tamanho da caixa “Descrição” deve ser um pouco maior.

**Comment by jasmimdsantos** [comment]
Dentro da aba " Impactos Sugeridos " dentro da opção "Implementar" o tamanho da aba "descriçao" deve ser um pouco maior e a caixa "Impacto" deve mostrar o impacto que foi sugerido,

**Comment by lucawen** [comment]
Corrigido em ee2c98efa4320ca74a373baa1858a0b0d4baf45c
